<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="11" passed="5">
  <reporter-output>
    <line>
      <![CDATA[
login into application with user name prachi.verma]]>
    </line>
    <line>
      <![CDATA[
Verify user prachi.verma login successfully]]>
    </line>
    <line>
      <![CDATA[
Select book store menu]]>
    </line>
    <line>
      <![CDATA[
Search book Git Pocket Guide]]>
    </line>
    <line>
      <![CDATA[
Select book Git Pocket Guide]]>
    </line>
    <line>
      <![CDATA[
Add Git Pocket Guide to your collection]]>
    </line>
    <line>
      <![CDATA[
Click on profile menu]]>
    </line>
    <line>
      <![CDATA[
Verify book added]]>
    </line>
    <line>
      <![CDATA[
remove book from profile]]>
    </line>
    <line>
      <![CDATA[
verify book removed from profile]]>
    </line>
    <line>
      <![CDATA[
login into application with user name prachi.verma]]>
    </line>
    <line>
      <![CDATA[
Verify user prachi.verma not login successfully]]>
    </line>
    <line>
      <![CDATA[Started execution of test create user]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"userID":"401d212f-5ad2-42ba-bca9-fd197a4f406d","username":"test1620498484130","books":[]}]]>
    </line>
    <line>
      <![CDATA[Verified response code 201]]>
    </line>
    <line>
      <![CDATA[Verified content type application/json]]>
    </line>
    <line>
      <![CDATA[Verify user name is response body]]>
    </line>
    <line>
      <![CDATA[Started execution of test get auth]]>
    </line>
    <line>
      <![CDATA[/Account/v1/Authorized]]>
    </line>
    <line>
      <![CDATA[true]]>
    </line>
    <line>
      <![CDATA[Verified response code 200]]>
    </line>
    <line>
      <![CDATA[Verified content type application/json]]>
    </line>
    <line>
      <![CDATA[Verify response is true]]>
    </line>
    <line>
      <![CDATA[Started execution of test create user without body]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"code":"1200","message":"UserName and Password required."}]]>
    </line>
    <line>
      <![CDATA[Verify user name is response body]]>
    </line>
    <line>
      <![CDATA[Started execution of test get user details for id 401d212f-5ad2-42ba-bca9-fd197a4f406d]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"code":"1200","message":"User not authorized!"}]]>
    </line>
    <line>
      <![CDATA[Verified response code 200]]>
    </line>
    <line>
      <![CDATA[Started execution of test delete user for id 401d212f-5ad2-42ba-bca9-fd197a4f406d]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"code":"1200","message":"User not authorized!"}]]>
    </line>
    <line>
      <![CDATA[Verified response code 200]]>
    </line>
    <line>
      <![CDATA[Started execution of test create user]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"code":"1204","message":"User exists!"}]]>
    </line>
    <line>
      <![CDATA[Verified response code 201]]>
    </line>
    <line>
      <![CDATA[Started execution of test create user]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"code":"1204","message":"User exists!"}]]>
    </line>
    <line>
      <![CDATA[Verified response code 201]]>
    </line>
    <line>
      <![CDATA[Started execution of test create user]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"code":"1204","message":"User exists!"}]]>
    </line>
    <line>
      <![CDATA[Verified response code 201]]>
    </line>
    <line>
      <![CDATA[Started execution of test create user]]>
    </line>
    <line>
      <![CDATA[/Account/v1/User]]>
    </line>
    <line>
      <![CDATA[{"code":"1204","message":"User exists!"}]]>
    </line>
    <line>
      <![CDATA[Verified response code 201]]>
    </line>
  </reporter-output>
  <suite name="TestSuite" duration-ms="83439" started-at="2021-05-08T18:26:55Z" finished-at="2021-05-08T18:28:18Z">
    <groups>
    </groups>
    <test name="UITests" duration-ms="66868" started-at="2021-05-08T18:26:55Z" finished-at="2021-05-08T18:28:02Z">
      <class name="com.test.selenium.Login">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.selenium.Login@1ed4004b]" name="setUp" is-config="true" duration-ms="3553" started-at="2021-05-08T23:57:52Z" finished-at="2021-05-08T23:57:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setTest(java.lang.reflect.Method)[pri:0, instance:com.test.selenium.Login@1ed4004b]" name="setTest" is-config="true" duration-ms="3246" started-at="2021-05-08T23:57:55Z" finished-at="2021-05-08T23:57:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.selenium.Login.testVerifyFailed()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTest -->
        <test-method status="PASS" signature="testVerifyFailed()[pri:0, instance:com.test.selenium.Login@1ed4004b]" name="testVerifyFailed" duration-ms="1924" started-at="2021-05-08T23:57:59Z" finished-at="2021-05-08T23:58:01Z">
          <reporter-output>
            <line>
              <![CDATA[
login into application with user name prachi.verma]]>
            </line>
            <line>
              <![CDATA[
Verify user prachi.verma not login successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testVerifyFailed -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.test.selenium.Login@1ed4004b]" name="afterClass" is-config="true" duration-ms="1120" started-at="2021-05-08T23:58:01Z" finished-at="2021-05-08T23:58:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.test.selenium.Login -->
      <class name="com.test.selenium.AddVerifyBook">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.selenium.AddVerifyBook@4566e5bd]" name="setUp" is-config="true" duration-ms="13097" started-at="2021-05-08T23:56:55Z" finished-at="2021-05-08T23:57:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setTest(java.lang.reflect.Method)[pri:0, instance:com.test.selenium.AddVerifyBook@4566e5bd]" name="setTest" is-config="true" duration-ms="3958" started-at="2021-05-08T23:57:08Z" finished-at="2021-05-08T23:57:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.selenium.AddVerifyBook.TestAddAndRemoveBookInCollection()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTest -->
        <test-method status="PASS" signature="TestAddAndRemoveBookInCollection()[pri:0, instance:com.test.selenium.AddVerifyBook@4566e5bd]" name="TestAddAndRemoveBookInCollection" duration-ms="38878" started-at="2021-05-08T23:57:12Z" finished-at="2021-05-08T23:57:51Z">
          <reporter-output>
            <line>
              <![CDATA[
login into application with user name prachi.verma]]>
            </line>
            <line>
              <![CDATA[
Verify user prachi.verma login successfully]]>
            </line>
            <line>
              <![CDATA[
Select book store menu]]>
            </line>
            <line>
              <![CDATA[
Search book Git Pocket Guide]]>
            </line>
            <line>
              <![CDATA[
Select book Git Pocket Guide]]>
            </line>
            <line>
              <![CDATA[
Add Git Pocket Guide to your collection]]>
            </line>
            <line>
              <![CDATA[
Click on profile menu]]>
            </line>
            <line>
              <![CDATA[
Verify book added]]>
            </line>
            <line>
              <![CDATA[
remove book from profile]]>
            </line>
            <line>
              <![CDATA[
verify book removed from profile]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestAddAndRemoveBookInCollection -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.test.selenium.AddVerifyBook@4566e5bd]" name="afterClass" is-config="true" duration-ms="996" started-at="2021-05-08T23:57:51Z" finished-at="2021-05-08T23:57:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.test.selenium.AddVerifyBook -->
    </test> <!-- UITests -->
    <test name="APITests" duration-ms="15679" started-at="2021-05-08T18:28:03Z" finished-at="2021-05-08T18:28:18Z">
      <class name="com.test.api.DataDrivenAPI">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="setup" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:13Z" finished-at="2021-05-08T23:58:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="setupMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:15Z" finished-at="2021-05-08T23:58:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.DataDrivenAPI.createUser(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="createUser" duration-ms="892" started-at="2021-05-08T23:58:15Z" data-provider="UserData" finished-at="2021-05-08T23:58:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User1111]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[P@ssw0rd]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<201> but was:<406>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<406>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.framework.util.BaseAPITest.verifyResponseCodeAndContentType(BaseAPITest.java:148)
	at com.test.api.DataDrivenAPI.createUser(DataDrivenAPI.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Started execution of test create user]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"code":"1204","message":"User exists!"}]]>
            </line>
            <line>
              <![CDATA[Verified response code 201]]>
            </line>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="testAfterMethod" is-config="true" duration-ms="6" started-at="2021-05-08T23:58:16Z" finished-at="2021-05-08T23:58:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createUser status=FAILURE method=DataDrivenAPI.createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d] output=Started execution of test create user]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="setupMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:16Z" finished-at="2021-05-08T23:58:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.DataDrivenAPI.createUser(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="createUser" duration-ms="888" started-at="2021-05-08T23:58:16Z" data-provider="UserData" finished-at="2021-05-08T23:58:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User2222]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[P@ssw0rd]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<201> but was:<406>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<406>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.framework.util.BaseAPITest.verifyResponseCodeAndContentType(BaseAPITest.java:148)
	at com.test.api.DataDrivenAPI.createUser(DataDrivenAPI.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Started execution of test create user]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"code":"1204","message":"User exists!"}]]>
            </line>
            <line>
              <![CDATA[Verified response code 201]]>
            </line>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="testAfterMethod" is-config="true" duration-ms="2" started-at="2021-05-08T23:58:17Z" finished-at="2021-05-08T23:58:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createUser status=FAILURE method=DataDrivenAPI.createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d] output=Started execution of test create user]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="setupMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:17Z" finished-at="2021-05-08T23:58:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.DataDrivenAPI.createUser(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="createUser" duration-ms="867" started-at="2021-05-08T23:58:17Z" data-provider="UserData" finished-at="2021-05-08T23:58:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User3333]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[P@ssw0rd]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<201> but was:<406>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<406>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.framework.util.BaseAPITest.verifyResponseCodeAndContentType(BaseAPITest.java:148)
	at com.test.api.DataDrivenAPI.createUser(DataDrivenAPI.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Started execution of test create user]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"code":"1204","message":"User exists!"}]]>
            </line>
            <line>
              <![CDATA[Verified response code 201]]>
            </line>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="testAfterMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:17Z" finished-at="2021-05-08T23:58:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createUser status=FAILURE method=DataDrivenAPI.createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d] output=Started execution of test create user]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="setupMethod" is-config="true" duration-ms="3" started-at="2021-05-08T23:58:17Z" finished-at="2021-05-08T23:58:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.DataDrivenAPI.createUser(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="createUser" duration-ms="883" started-at="2021-05-08T23:58:17Z" data-provider="UserData" finished-at="2021-05-08T23:58:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User4444]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[P@ssw0rd]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<201> but was:<406>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<406>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.framework.util.BaseAPITest.verifyResponseCodeAndContentType(BaseAPITest.java:148)
	at com.test.api.DataDrivenAPI.createUser(DataDrivenAPI.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Started execution of test create user]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"code":"1204","message":"User exists!"}]]>
            </line>
            <line>
              <![CDATA[Verified response code 201]]>
            </line>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d]" name="testAfterMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:18Z" finished-at="2021-05-08T23:58:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createUser status=FAILURE method=DataDrivenAPI.createUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.api.DataDrivenAPI@63753b6d] output=Started execution of test create user]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
      </class> <!-- com.test.api.DataDrivenAPI -->
      <class name="com.test.api.Account">
        <test-method status="PASS" signature="before()[pri:0, instance:com.test.api.Account@370736d9]" name="before" is-config="true" duration-ms="439" started-at="2021-05-08T23:56:54Z" finished-at="2021-05-08T23:56:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.test.api.Account@370736d9]" name="setup" is-config="true" duration-ms="1011" started-at="2021-05-08T23:58:03Z" finished-at="2021-05-08T23:58:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="createUser()[pri:0, instance:com.test.api.Account@370736d9]" name="createUser" duration-ms="5305" started-at="2021-05-08T23:58:04Z" finished-at="2021-05-08T23:58:09Z">
          <reporter-output>
            <line>
              <![CDATA[Started execution of test create user]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"userID":"401d212f-5ad2-42ba-bca9-fd197a4f406d","username":"test1620498484130","books":[]}]]>
            </line>
            <line>
              <![CDATA[Verified response code 201]]>
            </line>
            <line>
              <![CDATA[Verified content type application/json]]>
            </line>
            <line>
              <![CDATA[Verify user name is response body]]>
            </line>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.Account@370736d9]" name="setupMethod" is-config="true" duration-ms="0" started-at="2021-05-08T23:58:04Z" finished-at="2021-05-08T23:58:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.Account.createUser()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.Account@370736d9]" name="testAfterMethod" is-config="true" duration-ms="3" started-at="2021-05-08T23:58:09Z" finished-at="2021-05-08T23:58:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createUser status=SUCCESS method=Account.createUser()[pri:0, instance:com.test.api.Account@370736d9] output=Started execution of test create user]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.Account@370736d9]" name="setupMethod" is-config="true" duration-ms="0" started-at="2021-05-08T23:58:09Z" finished-at="2021-05-08T23:58:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.Account.getAth()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="getAth()[pri:0, instance:com.test.api.Account@370736d9]" name="getAth" duration-ms="1012" started-at="2021-05-08T23:58:09Z" finished-at="2021-05-08T23:58:10Z">
          <reporter-output>
            <line>
              <![CDATA[Started execution of test get auth]]>
            </line>
            <line>
              <![CDATA[/Account/v1/Authorized]]>
            </line>
            <line>
              <![CDATA[true]]>
            </line>
            <line>
              <![CDATA[Verified response code 200]]>
            </line>
            <line>
              <![CDATA[Verified content type application/json]]>
            </line>
            <line>
              <![CDATA[Verify response is true]]>
            </line>
          </reporter-output>
        </test-method> <!-- getAth -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.Account@370736d9]" name="testAfterMethod" is-config="true" duration-ms="0" started-at="2021-05-08T23:58:10Z" finished-at="2021-05-08T23:58:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getAth status=SUCCESS method=Account.getAth()[pri:0, instance:com.test.api.Account@370736d9] output=Started execution of test get auth]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.Account@370736d9]" name="setupMethod" is-config="true" duration-ms="3" started-at="2021-05-08T23:58:10Z" finished-at="2021-05-08T23:58:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.Account.verifyUnAuthUser()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="verifyUnAuthUser()[pri:0, instance:com.test.api.Account@370736d9]" name="verifyUnAuthUser" duration-ms="907" started-at="2021-05-08T23:58:10Z" finished-at="2021-05-08T23:58:11Z">
          <reporter-output>
            <line>
              <![CDATA[Started execution of test create user without body]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"code":"1200","message":"UserName and Password required."}]]>
            </line>
            <line>
              <![CDATA[Verify user name is response body]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyUnAuthUser -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.Account@370736d9]" name="testAfterMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:11Z" finished-at="2021-05-08T23:58:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUnAuthUser status=SUCCESS method=Account.verifyUnAuthUser()[pri:0, instance:com.test.api.Account@370736d9] output=Started execution of test create user without body]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.Account@370736d9]" name="setupMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:11Z" finished-at="2021-05-08T23:58:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.Account.getUserById()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="getUserById()[pri:0, instance:com.test.api.Account@370736d9]" name="getUserById" duration-ms="1706" started-at="2021-05-08T23:58:11Z" depends-on-methods="com.test.api.Account.createUser" finished-at="2021-05-08T23:58:13Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<200> but was:<401>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<401>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.framework.util.BaseAPITest.verifyResponseCodeAndContentType(BaseAPITest.java:148)
	at com.test.api.Account.getUserById(Account.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Started execution of test get user details for id 401d212f-5ad2-42ba-bca9-fd197a4f406d]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"code":"1200","message":"User not authorized!"}]]>
            </line>
            <line>
              <![CDATA[Verified response code 200]]>
            </line>
          </reporter-output>
        </test-method> <!-- getUserById -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.Account@370736d9]" name="testAfterMethod" is-config="true" duration-ms="2" started-at="2021-05-08T23:58:13Z" finished-at="2021-05-08T23:58:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getUserById status=FAILURE method=Account.getUserById()[pri:0, instance:com.test.api.Account@370736d9] output=Started execution of test get user details for id 401d212f-5ad2-42ba-bca9-fd197a4f406d]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method)[pri:0, instance:com.test.api.Account@370736d9]" name="setupMethod" is-config="true" duration-ms="0" started-at="2021-05-08T23:58:13Z" finished-at="2021-05-08T23:58:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.api.Account.deletetUser()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="deletetUser()[pri:0, instance:com.test.api.Account@370736d9]" name="deletetUser" duration-ms="897" started-at="2021-05-08T23:58:13Z" depends-on-methods="com.test.api.Account.getUserById" finished-at="2021-05-08T23:58:13Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<200> but was:<401>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<401>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.framework.util.BaseAPITest.verifyResponseCodeAndContentType(BaseAPITest.java:148)
	at com.test.api.Account.deletetUser(Account.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Started execution of test delete user for id 401d212f-5ad2-42ba-bca9-fd197a4f406d]]>
            </line>
            <line>
              <![CDATA[/Account/v1/User]]>
            </line>
            <line>
              <![CDATA[{"code":"1200","message":"User not authorized!"}]]>
            </line>
            <line>
              <![CDATA[Verified response code 200]]>
            </line>
          </reporter-output>
        </test-method> <!-- deletetUser -->
        <test-method status="PASS" signature="testAfterMethod(org.testng.ITestResult)[pri:0, instance:com.test.api.Account@370736d9]" name="testAfterMethod" is-config="true" duration-ms="1" started-at="2021-05-08T23:58:13Z" finished-at="2021-05-08T23:58:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deletetUser status=FAILURE method=Account.deletetUser()[pri:0, instance:com.test.api.Account@370736d9] output=Started execution of test delete user for id 401d212f-5ad2-42ba-bca9-fd197a4f406d]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterMethod -->
        <test-method status="PASS" signature="tearDownSuite()[pri:0, instance:com.test.api.Account@370736d9]" name="tearDownSuite" is-config="true" duration-ms="123" started-at="2021-05-08T23:58:19Z" finished-at="2021-05-08T23:58:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- com.test.api.Account -->
    </test> <!-- APITests -->
  </suite> <!-- TestSuite -->
</testng-results>
